version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:

      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress

  web:
    build:
     context: ./
     dockerfile: Dockerfile
    restart: always
    volumes:
      - ./wp_data:/var/www/html


#    extra_hosts:
#        - "yourdomain.com:127.0.0.1"

    ports:
            - "80:80"
            - "443:443"

#    environment:

#     DB_HOST: db:3306

#      DB_NAME: wordpress
#      DB_USER: root
#      DB_PASSWORD: password
    depends_on:
       - db


