version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:

      - ./shared:/var/lib/shared
      - ./database/data:/var/lib/mysql
      - ./database/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links: 
     - db
    ports: 
     - 9100:80
    depends_on:
     - db

  web:
    build:
     context: ./
     dockerfile: Dockerfile
    restart: always
    volumes:
      - ./wp_data:/var/www/html


#    extra_hosts:
#        - "winkenhk.com:127.0.0.1"

    ports:
            - "80:80"
            - "443:443"
#    environment:

#      WORDPRESS_DB_HOST: db:3306

#      WORDPRESS_DB_NAME: wordpress
#      WORDPRESS_DB_USER: root
#      WORDPRESS_DB_PASSWORD: password
    depends_on:
       - db


